# Generated by Django 5.2.11 on 2026-02-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_alter_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='files',
            field=models.FileField(default=1, upload_to='files/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
