# Generated by Django 5.2.11 on 2026-02-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_department_person_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_id', models.CharField(max_length=20)),
                ('e_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=15)),
                ('hr_status', models.CharField(max_length=50)),
                ('admin_status', models.CharField(max_length=50)),
            ],
        ),
    ]
