# Generated by Django 5.2.11 on 2026-02-23 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_emp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp',
            old_name='department',
            new_name='dept',
        ),
    ]
